# Generated by Django 4.1.7 on 2023-03-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('peso', models.TextField()),
                ('altura', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('imagem', models.CharField(max_length=200)),
            ],
        ),
    ]
